package io.github.opencivilizationplatform.modules.social;

import io.github.opencivilizationplatform.modules.social.application.CivilizationChronicleService;
import io.github.opencivilizationplatform.modules.social.domain.ChronicleEntry;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

class CivilizationChronicleServiceTest {

    private CivilizationChronicleService service;

    @BeforeEach
    void setUp() {
        service = new CivilizationChronicleService();
    }

    @Test
    void testRecordAndGetEntry() {
        ChronicleEntry entry = service.recordEntry("entry-1", 100L, "DIPLOMACY", "Peace treaty signed between factions.");
        assertNotNull(entry);
        assertEquals("entry-1", entry.entryId());
        assertEquals(100L, entry.tick());
        assertEquals("DIPLOMACY", entry.category());
        assertEquals("Peace treaty signed between factions.", entry.description());

        Optional<ChronicleEntry> retrieved = service.getEntryById("entry-1");
        assertTrue(retrieved.isPresent());
        assertEquals("entry-1", retrieved.get().entryId());
    }

    @Test
    void testRecordEntryAutoGeneratedId() {
        ChronicleEntry entry = service.recordEntry(50L, "DISCOVERY", "Discovered metallurgy.");
        assertNotNull(entry);
        assertNotNull(entry.entryId());
        assertEquals(50L, entry.tick());
        assertEquals("DISCOVERY", entry.category());
    }

    @Test
    void testGetEntriesByCategory() {
        service.recordEntry("e1", 10L, "ERA_SHIFT", "Entered Bronze Age");
        service.recordEntry("e2", 20L, "EPIDEMIC", "Plague outbreak in capital");
        service.recordEntry("e3", 30L, "ERA_SHIFT", "Entered Iron Age");

        List<ChronicleEntry> eraShifts = service.getEntriesByCategory("ERA_SHIFT");
        assertEquals(2, eraShifts.size());
    }

    @Test
    void testGetEntriesByTickRange() {
        service.recordEntry("e1", 10L, "EVENT", "Event at 10");
        service.recordEntry("e2", 20L, "EVENT", "Event at 20");
        service.recordEntry("e3", 30L, "EVENT", "Event at 30");

        List<ChronicleEntry> range = service.getEntriesByTickRange(15L, 25L);
        assertEquals(1, range.size());
        assertEquals("e2", range.get(0).entryId());
    }

    @Test
    void testProcessChronicleTick() {
        service.recordEntry(1L, "FOUNDATION", "Civilization founded");
        assertDoesNotThrow(() -> service.processChronicleTick());
    }
}
